### ISSUE TITLE
Crash with Environmental Mod

### ISSUE THREAD

**Issue by Shads404** [babybluetit/Xaeros-Minimap-Modded-Support#19] opened 2022-01-07 15:49 UTC
Latest version of Better MC 1.16.5 is crashing when attempting to render the yak from environmental.   Removing the resource pack resolves the issue.    Pastebin of the relevant part of the crash here:  https://pastebin.com/eMt4ZELb

**Comment by babybluetit** [comment] 2022-01-07 15:57
Thank you for reporting! This has been fixed now and I've uploaded the safe version of the pack to Curseforge.

**Closed by babybluetit** 2022-01-07 15:57 UTC

**Comment by thexaero** [comment] 2022-01-07 17:11
Surely it wasn't actually crashing, just logging the exception?

**Comment by babybluetit** [comment] 2022-01-07 17:34
I've just checked this and on my singleplayer world the faulty version didn't result in a crash - it just logged the exception like you said. 
So I'm unsure if the issue is solely with the resourcepack but at least it shouldn't occur again.

**Comment by thexaero** [comment] 2022-01-07 19:39
That's what it's supposed to do, so I hope that's the case lol
